/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.botoe_janelas_eventos;

/**
 *
 * @author v.silva
 */
public class novoForm extends javax.swing.JFrame {

    /**
     * Creates new form novoForm
     */
    public novoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_connectado = new javax.swing.JLabel();
        jLabel_achou = new javax.swing.JLabel();
        jLabel_desconecado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox_1 = new javax.swing.JComboBox<>();
        jLabel_combo_selected = new javax.swing.JLabel();
        jCheckBox = new javax.swing.JCheckBox();
        jRadioButton = new javax.swing.JRadioButton();
        jLabel_check_box = new javax.swing.JLabel();
        jLabel_RadioButton1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_connectado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_connectado.setText("Connectado");
        getContentPane().add(jLabel_connectado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel_achou.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_achou.setText("ACHOU!!");
        getContentPane().add(jLabel_achou, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel_desconecado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_desconecado.setText("Desconecado");
        getContentPane().add(jLabel_desconecado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jButton1.setText("ocultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jButton2.setText("exibir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jComboBox_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "carro", "avião", "barco", "bike" }));
        getContentPane().add(jComboBox_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 150, -1));

        jLabel_combo_selected.setText("combo_selected");
        getContentPane().add(jLabel_combo_selected, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jCheckBox.setText("CheckBox");
        getContentPane().add(jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jRadioButton.setText("RadioButton");
        getContentPane().add(jRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        jLabel_check_box.setText("Label_RadioButton");
        getContentPane().add(jLabel_check_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        jLabel_RadioButton1.setText("Label_check_box");
        getContentPane().add(jLabel_RadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel_achou.setVisible(true);
        jLabel_connectado.setVisible(true);
        jLabel_desconecado.setVisible(false);
        
              
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel_achou.setVisible(false);
        jLabel_connectado.setVisible(false);
        jLabel_desconecado.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabel_achou.setVisible(false);
        jLabel_connectado.setVisible(false);
        jLabel_desconecado.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String selecionado = (String) jComboBox_1.getSelectedItem();
        jLabel_combo_selected.setText(selecionado);
        jLabel_check_box.setText("Checkbox Selecionado : " + Boolean.toString(jCheckBox.isSelected()));
        jLabel_RadioButton1.setText("Checkbox Selecionado : " + Boolean.toString(jRadioButton.isSelected()));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(novoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(novoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(novoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(novoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new novoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JComboBox<String> jComboBox_1;
    private javax.swing.JLabel jLabel_RadioButton1;
    private javax.swing.JLabel jLabel_achou;
    private javax.swing.JLabel jLabel_check_box;
    private javax.swing.JLabel jLabel_combo_selected;
    private javax.swing.JLabel jLabel_connectado;
    private javax.swing.JLabel jLabel_desconecado;
    private javax.swing.JRadioButton jRadioButton;
    // End of variables declaration//GEN-END:variables
}
