/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author v.silva
 */
public class CRUDFORM extends javax.swing.JFrame {

    /**
     * Creates new form CRUDFORM
     */
    public CRUDFORM() {
        initComponents();
        jlbl_infor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_home = new javax.swing.JPanel();
        jbtn_Inserir = new javax.swing.JButton();
        jbtn_atualizar = new javax.swing.JButton();
        jbtn_excluir = new javax.swing.JButton();
        jbtn_encontrar = new javax.swing.JButton();
        jtxtf_RA_ALUN = new javax.swing.JTextField();
        jtxtf_NOME_ALU = new javax.swing.JTextField();
        jtxtf_DT_NASC_ALU = new javax.swing.JTextField();
        jtxtf_CPF_ALU = new javax.swing.JTextField();
        jtxtf_SEXO_ALU = new javax.swing.JTextField();
        jlbl_RA = new javax.swing.JLabel();
        jlbl_NomeAluno = new javax.swing.JLabel();
        jlbl_dt_nasc = new javax.swing.JLabel();
        jlbl_CPF = new javax.swing.JLabel();
        jlbl_sexo = new javax.swing.JLabel();
        jbtn_sair = new javax.swing.JButton();
        jlbl_infor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(560, 370));
        setName("CRUD"); // NOI18N
        setPreferredSize(new java.awt.Dimension(560, 370));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jpnl_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_Inserir.setText("Inserir");
        jbtn_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_InserirActionPerformed(evt);
            }
        });
        jpnl_home.add(jbtn_Inserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 240, -1, -1));

        jbtn_atualizar.setText("atualizar");
        jpnl_home.add(jbtn_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 240, -1, -1));

        jbtn_excluir.setText("excluir");
        jpnl_home.add(jbtn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 240, -1, -1));

        jbtn_encontrar.setText("encontrar");
        jbtn_encontrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_encontrarActionPerformed(evt);
            }
        });
        jpnl_home.add(jbtn_encontrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jtxtf_RA_ALUN.setEnabled(false);
        jtxtf_RA_ALUN.setPreferredSize(new java.awt.Dimension(70, 22));
        jpnl_home.add(jtxtf_RA_ALUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 19, 70, -1));
        jpnl_home.add(jtxtf_NOME_ALU, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 59, 232, -1));
        jpnl_home.add(jtxtf_DT_NASC_ALU, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 141, 122, -1));
        jpnl_home.add(jtxtf_CPF_ALU, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 101, 108, -1));
        jpnl_home.add(jtxtf_SEXO_ALU, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 181, 122, -1));

        jlbl_RA.setText("Registro Academico :");
        jpnl_home.add(jlbl_RA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jlbl_NomeAluno.setText("Nome Aluno :");
        jpnl_home.add(jlbl_NomeAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jlbl_dt_nasc.setText("Data Nascimento : ");
        jpnl_home.add(jlbl_dt_nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 144, -1, -1));

        jlbl_CPF.setText("CPF ");
        jpnl_home.add(jlbl_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 104, -1, -1));

        jlbl_sexo.setText("Sexo : ");
        jpnl_home.add(jlbl_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 184, -1, -1));

        jbtn_sair.setText("Sair");
        jbtn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_sairActionPerformed(evt);
            }
        });
        jpnl_home.add(jbtn_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 281, 254, -1));

        jlbl_infor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbl_infor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_infor.setText("TESTE");
        jlbl_infor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpnl_home.add(jlbl_infor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 210, 102));

        getContentPane().add(jpnl_home);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_InserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_InserirActionPerformed

    private void jbtn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_sairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtn_sairActionPerformed

    private void jbtn_encontrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_encontrarActionPerformed
        // TODO add your handling code here:
                try {
        Connection conexao = null;
        PreparedStatement statement = null;
        
        String url = "jdbc:mysql://localhost:3306/escolasenai";
        String usuario = "root";
        String senha = "";
        
        conexao = DriverManager.getConnection(url,usuario,senha);
        String sql = "SELECT * FROM tb_aluno WHERE nome_alu = ?";
//        String sql = "SELECT * FROM tb_aluno GROU BY nome_alu HAVING nome_alu= ?";
        statement = conexao.prepareStatement(sql);
        statement.setString(1, jtxtf_NOME_ALU.getText());
        
        ResultSet resultSet = statement.executeQuery();
        
        if (resultSet.next()){
            String RA_ALUN = resultSet.getString("RA_ALUN");
            jtxtf_RA_ALUN.setText(RA_ALUN);
            String NOME_ALU = resultSet.getString("NOME_ALU");
            jtxtf_NOME_ALU.setText(NOME_ALU);
            String CPF_ALU = resultSet.getString("CPF_ALU");
            jtxtf_CPF_ALU.setText(CPF_ALU);
            String DT_NASC_ALU = resultSet.getString("DT_NASC_ALU");
            jtxtf_DT_NASC_ALU.setText(DT_NASC_ALU);
            String SEXO_ALU = resultSet.getString("SEXO_ALU");
            jtxtf_SEXO_ALU.setText(SEXO_ALU);
            jlbl_infor.setText("OK");
        } else {
            jlbl_infor.setText("Não Encontrado");
            jlbl_infor.setVisible(true);
        }
        
        resultSet.close();
        statement.close();
        conexao.close();
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
            jlbl_infor.setText("Não Encontrado");
            jlbl_infor.setVisible(true);
        }
    }//GEN-LAST:event_jbtn_encontrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_Inserir;
    private javax.swing.JButton jbtn_atualizar;
    private javax.swing.JButton jbtn_encontrar;
    private javax.swing.JButton jbtn_excluir;
    private javax.swing.JButton jbtn_sair;
    private javax.swing.JLabel jlbl_CPF;
    private javax.swing.JLabel jlbl_NomeAluno;
    private javax.swing.JLabel jlbl_RA;
    private javax.swing.JLabel jlbl_dt_nasc;
    private javax.swing.JLabel jlbl_infor;
    private javax.swing.JLabel jlbl_sexo;
    private javax.swing.JPanel jpnl_home;
    private javax.swing.JTextField jtxtf_CPF_ALU;
    private javax.swing.JTextField jtxtf_DT_NASC_ALU;
    private javax.swing.JTextField jtxtf_NOME_ALU;
    private javax.swing.JTextField jtxtf_RA_ALUN;
    private javax.swing.JTextField jtxtf_SEXO_ALU;
    // End of variables declaration//GEN-END:variables
}
