/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author v.silva
 */
public class CRUDFORM extends javax.swing.JFrame {

    /**
     * Creates new form CRUDFORM
     */
    public CRUDFORM() {
        initComponents();
        jlbl_infor.setVisible(false);
    }
    public void listagemCompleta(String sql) {
        try
            {
             Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/escolasenai2", "root", "");
             PreparedStatement banco = (PreparedStatement)con.prepareStatement(sql);
             banco.execute(); // cria o vetor

             ResultSet resultado = banco.executeQuery(sql);

             DefaultTableModel model =(DefaultTableModel) jtbl_aluno.getModel();
             model.setNumRows(0);

             while(resultado.next())
             {
                 model.addRow(new Object[] 
                 { 
                    resultado.getString("aluno_ra"),
                    resultado.getString("ALUNO_NOME"),
                    resultado.getString("aluno_dt_nasc"),
                    resultado.getString("aluno_cpf"),
                    resultado.getString("aluno_sexo")

                 }); 
            } 
             banco.close();
             con.close();
            }
           catch (SQLException ex)
           {
              System.out.println("o erro foi " +ex);
              }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_home = new javax.swing.JPanel();
        jbtn_Inserir = new javax.swing.JButton();
        jbtn_atualizar = new javax.swing.JButton();
        jbtn_excluir = new javax.swing.JButton();
        jbtn_encontrar = new javax.swing.JButton();
        jtxtf_RA_ALUNO = new javax.swing.JTextField();
        jtxtf_NOME_ALUNO = new javax.swing.JTextField();
        jtxtf_DT_NASC_ALUNO = new javax.swing.JTextField();
        jtxtf_CPF_ALUNO = new javax.swing.JTextField();
        jcmb_SEXO_ALUNO = new javax.swing.JComboBox<>();
        jlbl_RA = new javax.swing.JLabel();
        jlbl_NomeAluno = new javax.swing.JLabel();
        jlbl_dt_nasc = new javax.swing.JLabel();
        jlbl_CPF = new javax.swing.JLabel();
        jlbl_sexo = new javax.swing.JLabel();
        jbtn_sair = new javax.swing.JButton();
        jlbl_infor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_aluno = new javax.swing.JTable();
        jbtn_listagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1066, 344));
        setName("CRUD"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1066, 344));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jpnl_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_Inserir.setText("Inserir");
        jbtn_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_InserirActionPerformed(evt);
            }
        });
        jpnl_home.add(jbtn_Inserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 220, -1, -1));

        jbtn_atualizar.setText("atualizar");
        jbtn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_atualizarActionPerformed(evt);
            }
        });
        jpnl_home.add(jbtn_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 220, -1, -1));

        jbtn_excluir.setText("excluir");
        jbtn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_excluirActionPerformed(evt);
            }
        });
        jpnl_home.add(jbtn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 220, -1, -1));

        jbtn_encontrar.setText("encontrar");
        jbtn_encontrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_encontrarActionPerformed(evt);
            }
        });
        jpnl_home.add(jbtn_encontrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 56, -1, -1));

        jtxtf_RA_ALUNO.setEnabled(false);
        jtxtf_RA_ALUNO.setPreferredSize(new java.awt.Dimension(70, 22));
        jpnl_home.add(jtxtf_RA_ALUNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 19, 40, -1));
        jpnl_home.add(jtxtf_NOME_ALUNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 59, 232, -1));
        jpnl_home.add(jtxtf_DT_NASC_ALUNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 141, 80, -1));
        jpnl_home.add(jtxtf_CPF_ALUNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 101, 108, -1));

        jcmb_SEXO_ALUNO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jpnl_home.add(jcmb_SEXO_ALUNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 180, 80, -1));

        jlbl_RA.setText("Registro Academico :");
        jpnl_home.add(jlbl_RA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jlbl_NomeAluno.setText("Nome Aluno :");
        jpnl_home.add(jlbl_NomeAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jlbl_dt_nasc.setText("Data Nascimento : ");
        jpnl_home.add(jlbl_dt_nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 144, -1, -1));

        jlbl_CPF.setText("CPF ");
        jpnl_home.add(jlbl_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 104, -1, -1));

        jlbl_sexo.setText("Sexo : ");
        jpnl_home.add(jlbl_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 184, -1, -1));

        jbtn_sair.setText("Sair");
        jbtn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_sairActionPerformed(evt);
            }
        });
        jpnl_home.add(jbtn_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 260, 254, -1));

        jlbl_infor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbl_infor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_infor.setText("Status");
        jlbl_infor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpnl_home.add(jlbl_infor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 210, 102));

        jtbl_aluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Registro", "Nome", "Data", "CPF", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbl_aluno);
        if (jtbl_aluno.getColumnModel().getColumnCount() > 0) {
            jtbl_aluno.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtbl_aluno.getColumnModel().getColumn(1).setPreferredWidth(310);
            jtbl_aluno.getColumnModel().getColumn(2).setResizable(false);
            jtbl_aluno.getColumnModel().getColumn(2).setPreferredWidth(106);
            jtbl_aluno.getColumnModel().getColumn(3).setResizable(false);
            jtbl_aluno.getColumnModel().getColumn(3).setPreferredWidth(130);
            jtbl_aluno.getColumnModel().getColumn(4).setResizable(false);
            jtbl_aluno.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jpnl_home.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, 220));

        jbtn_listagem.setText("Listagem de alunos");
        jbtn_listagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listagemActionPerformed(evt);
            }
        });
        jpnl_home.add(jbtn_listagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 450, -1));

        getContentPane().add(jpnl_home);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_InserirActionPerformed
        // TODO add your handling code here:
        Connection conexao = null;
        PreparedStatement statement = null;
       
        String url = "jdbc:mysql://localhost:3306/escolasenai2";
        String usuario = "root";
        String senha = "";
        
       try {
            conexao = DriverManager.getConnection(url, usuario, senha);
           
            String sql = "INSERT INTO aluno (aluno_nome, aluno_cpf, aluno_dt_nasc, aluno_sexo) VALUES (? , ?, ?, ?)";
           
            statement = conexao.prepareStatement(sql);
            
             
            statement.setString(1, jtxtf_NOME_ALUNO.getText());
            statement.setString(2, jtxtf_CPF_ALUNO.getText());
            statement.setString(3, jtxtf_DT_NASC_ALUNO.getText());
            statement.setString(4, (String) jcmb_SEXO_ALUNO.getSelectedItem());
           
            //statement.execute();
           
            int linhasAfetadas = statement.executeUpdate();
           
            if (linhasAfetadas > 0) {
               
                jlbl_infor.setVisible(true);
                jlbl_infor.setText("Inserido com sucesso");
                System.out.println("Dados inseridos com sucesso!");
                this.listagemCompleta("SELECT * FROM aluno ORDER BY aluno_nome ASC");
                
            } else {
                jlbl_infor.setVisible(true);
                jlbl_infor.setText("Nenhum dado inserido.");
                System.out.println("Nenhum dado inserido.");
            }
         } catch (SQLException e) {
            System.out.println("Erro ao inserir dados: " + e.getMessage());
        } finally {
            try {
                if (statement != null) {
                    statement.close();
                }
                if (conexao != null) {
                    conexao.close();
                }
            } catch (SQLException e) {
                System.out.println("Erro ao fechar conexão: " + e.getMessage());
            }
       }        
        
    }//GEN-LAST:event_jbtn_InserirActionPerformed

    private void jbtn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_sairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtn_sairActionPerformed

    private void jbtn_encontrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_encontrarActionPerformed
        // TODO add your handling code here:
                try {
        Connection conexao = null;
        PreparedStatement statement = null;
        
        String url = "jdbc:mysql://localhost:3306/escolasenai2";
        String usuario = "root";
        String senha = "";
        
        conexao = DriverManager.getConnection(url,usuario,senha);
        String sql = "SELECT * FROM aluno WHERE aluno_nome = ?";
        statement = conexao.prepareStatement(sql);
        statement.setString(1, jtxtf_NOME_ALUNO.getText());
        
        ResultSet resultSet = statement.executeQuery();
        
        if (resultSet.next()){
            String RA_ALUN = resultSet.getString("ALUNO_RA");
            jtxtf_RA_ALUNO.setText(RA_ALUN);
            String NOME_ALU = resultSet.getString("ALUNO_NOME");
            jtxtf_NOME_ALUNO.setText(NOME_ALU);
            String CPF_ALU = resultSet.getString("ALUNO_CPF");
            jtxtf_CPF_ALUNO.setText(CPF_ALU);
            String DT_NASC_ALU = resultSet.getString("ALUNO_DT_NASC");
            jtxtf_DT_NASC_ALUNO.setText(DT_NASC_ALU);
            String SEXO_ALU = resultSet.getString("ALUNO_SEXO");
            jcmb_SEXO_ALUNO.setSelectedItem(SEXO_ALU);
            jlbl_infor.setText("OK");
        } else {
            jlbl_infor.setText("Não Encontrado");
            jlbl_infor.setVisible(true);
        }
        
        resultSet.close();
        statement.close();
        conexao.close();
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
            jlbl_infor.setText("Não Encontrado");
            jlbl_infor.setVisible(true);
        }
    }//GEN-LAST:event_jbtn_encontrarActionPerformed

    private void jbtn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_atualizarActionPerformed
        // TODO add your handling code here:
        Connection conexao = null;
        PreparedStatement statement = null;
       
        String url = "jdbc:mysql://localhost:3306/escolasenai2";
        String usuario = "root";
        String senha = "";
        
       try {
            conexao = DriverManager.getConnection(url, usuario, senha);
         
            String sql = "UPDATE aluno SET aluno_nome = ? , aluno_cpf = ?, aluno_dt_nasc = ?, aluno_sexo = ? where aluno_ra= ?";
            
            statement = conexao.prepareStatement(sql);
            
            statement.setString(1, jtxtf_NOME_ALUNO.getText());
            statement.setString(2, jtxtf_CPF_ALUNO.getText());
            statement.setString(3, jtxtf_DT_NASC_ALUNO.getText());
            statement.setString(4, (String) jcmb_SEXO_ALUNO.getSelectedItem());
            statement.setString(5, jtxtf_RA_ALUNO.getText());

            //statement.setString(1, jTextPane1_ID.getText());
/*
            statement.setString(1, jTextPane8.getText()); // NOME
            statement.setString(2, jTextPane9.getText()); // CPF
            statement.setString(3, jTextPane7.getText()); // ID
*/
           
            int linhasAfetadas = statement.executeUpdate();
           
            if (linhasAfetadas > 0) {
                jlbl_infor.setText("Dados atualizados");
                jlbl_infor.setVisible(true);
                System.out.println("Dados atualizados com sucesso!");
                this.listagemCompleta("SELECT * FROM aluno ORDER BY aluno_nome ASC");
            } else {
                jlbl_infor.setText("Nenhuma atualização");
                jlbl_infor.setVisible(true);
                System.out.println("Nenhum dado atualizado.");
            }
         } catch (SQLException e) {
            System.out.println("Erro ao atualizar dados: " + e.getMessage());
        } finally {
            try {
                if (statement != null) {
                    statement.close();
                }
                if (conexao != null) {
                    conexao.close();
                }
            } catch (SQLException e) {
                System.out.println("Erro ao fechar conexão: " + e.getMessage());
            }} 
       
    }//GEN-LAST:event_jbtn_atualizarActionPerformed

    private void jbtn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_excluirActionPerformed
        // TODO add your handling code here:
        Connection conexao = null;
        PreparedStatement statement = null;
        String url = "jdbc:mysql://localhost:3306/escolasenai2";
        String usuario = "root";
        String senha = "";
        
        try {
            
            conexao = DriverManager.getConnection(url, usuario, senha);
            String sql = "DELETE from aluno where aluno_ra = ?";
           
            statement = conexao.prepareStatement(sql);
            statement.setString(1, jtxtf_RA_ALUNO.getText());
           
            int linhasAfetadas = statement.executeUpdate();
           
            if (linhasAfetadas > 0) {
                jlbl_infor.setText("Dados excluidos");
                jlbl_infor.setVisible(true);
                System.out.println("Dados excluidos com sucesso!");
                this.listagemCompleta("SELECT * FROM aluno ORDER BY aluno_nome ASC");
            } else {
                jlbl_infor.setText("Nenhum dado excluido.");
                jlbl_infor.setVisible(true);
                System.out.println("Nenhum dado excluido.");
            }
        } catch (SQLException e) {
            System.out.println("Erro ao EXCLUIR dados: " + e.getMessage());
        } finally {
            try {
                if (statement != null) {
                    statement.close();
                }
                if (conexao != null) {
                    conexao.close();
                }
            } catch (SQLException e) {
                System.out.println("Erro ao fechar conexão: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jbtn_excluirActionPerformed

    private void jbtn_listagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listagemActionPerformed
        // TODO add your handling code here:
        this.listagemCompleta("SELECT * FROM aluno ORDER BY aluno_nome ASC");
    }//GEN-LAST:event_jbtn_listagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_Inserir;
    private javax.swing.JButton jbtn_atualizar;
    private javax.swing.JButton jbtn_encontrar;
    private javax.swing.JButton jbtn_excluir;
    private javax.swing.JButton jbtn_listagem;
    private javax.swing.JButton jbtn_sair;
    private javax.swing.JComboBox<String> jcmb_SEXO_ALUNO;
    private javax.swing.JLabel jlbl_CPF;
    private javax.swing.JLabel jlbl_NomeAluno;
    private javax.swing.JLabel jlbl_RA;
    private javax.swing.JLabel jlbl_dt_nasc;
    private javax.swing.JLabel jlbl_infor;
    private javax.swing.JLabel jlbl_sexo;
    private javax.swing.JPanel jpnl_home;
    private javax.swing.JTable jtbl_aluno;
    private javax.swing.JTextField jtxtf_CPF_ALUNO;
    private javax.swing.JTextField jtxtf_DT_NASC_ALUNO;
    private javax.swing.JTextField jtxtf_NOME_ALUNO;
    private javax.swing.JTextField jtxtf_RA_ALUNO;
    // End of variables declaration//GEN-END:variables
}
